export type BirdRarity = "common" | "rare" | "legendary";
export type BirdHabitat = "forest" | "wetland" | "grassland" | "mountain" | "desert" | "arctic" | "ocean" | "urban" | "oak woodland" | "gardens" | "coast" | "shrubland";
export type BirdSize = "tiny" | "small" | "medium" | "large" | "huge";

export interface Bird {
  id: string;
  name: string;
  ability: string;
  rarity: BirdRarity;
  description: string;
  funFact: string;
  habitat: BirdHabitat;
  size: BirdSize;
  imageUrl: string;
  additionalImages: string[];
  colors: string[]; // Main colors of the bird for confetti and theming
}

// Helper function to convert color names to hex codes
const colorMap: Record<string, string> = {
  "Brown": "#8B4513",
  "Gray": "#808080", 
  "Grey": "#808080",
  "Black": "#000000",
  "Red": "#FF0000",
  "Yellow": "#FFD700",
  "Orange": "#FFA500",
  "Blue": "#0000FF",
  "Green": "#008000",
  "White": "#FFFFFF",
  "Pink": "#FFC0CB",
  "Purple": "#800080",
  "Violet": "#8A2BE2"
};

// Helper function to parse colors from CSV format
function parseColors(colorString: string): string[] {
  if (!colorString) return ["#808080"];
  
  return colorString.split(",")
    .map(color => color.trim())
    .map(color => colorMap[color] || "#808080");
}

export const birds: Bird[] = [
  {
    id: "1",
    name: "Western Sandpiper",
    ability: "Tiny Tidal Treader",
    rarity: "rare",
    description: "A tiny shorebird that scurries along mudflats hunting for insects and crustaceans. Their quick movements make them a fun challenge to spot. They travel in large flocks during migration.",
    funFact: "Can eat almost 10% of its body weight in tiny invertebrates every day during migration.",
    habitat: "coast",
    size: "small",
    imageUrl: "/images/birds/western-sandpiper/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray")
  },
  {
    id: "2",
    name: "Red-winged Blackbird",
    ability: "Marsh Maestro",
    rarity: "common",
    description: "Males sport bright red and yellow shoulder patches, making them unmistakable. They dominate marshes with their loud, raucous calls. Watch for their bold displays during breeding season.",
    funFact: "Males can sing up to 100 different song variations to defend their territory.",
    habitat: "wetland",
    size: "small",
    imageUrl: "/images/birds/red-winged-blackbird/main.png",
    additionalImages: [],
    colors: parseColors("Black, Red, Yellow")
  },
  {
    id: "3",
    name: "Varied Thrush",
    ability: "Forest Songstress",
    rarity: "rare",
    description: "A striking forest bird with an orange breast and dark eye stripe. They sing haunting, melodic phrases at dawn. Often found quietly perched in dense woodlands.",
    funFact: "Their haunting song can mimic other birds, making them tricky to identify by sound alone.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/varied-thrush/main.png",
    additionalImages: [],
    colors: parseColors("Orange, Black, Blue")
  },
  {
    id: "4",
    name: "White-crowned sparrow",
    ability: "Stripe Strike",
    rarity: "common",
    description: "Recognizable by bold black-and-white head stripes. They forage on the ground for seeds and insects. Their clear, whistled songs are a favorite among birders.",
    funFact: "Young birds \"practice\" singing for weeks before mastering the adult song.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/white-crowned-sparrow/main.png",
    additionalImages: [],
    colors: parseColors("Gray, White, Black")
  },
  {
    id: "5",
    name: "Pygmy Nuthatch",
    ability: "Mini Bark Clinger",
    rarity: "common",
    description: "Tiny and energetic, darting up and down tree trunks for insects. They travel in tight family groups and communicate with soft, buzzing calls. Usually spotted in pine forests.",
    funFact: "They often sleep huddled in tree cavities, sometimes with 20 or more birds together.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/pygmy-nuthatch/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray")
  },
  {
    id: "6",
    name: "Ruby-crowned Kinglet",
    ability: "Ruby Flash",
    rarity: "common",
    description: "A tiny, lively bird with a hidden ruby crown that flashes when excited. Constantly on the move, flitting among branches for insects. Despite their small size, they have a big personality.",
    funFact: "The ruby crown is usually hidden and only flashes when the bird is excited or alarmed.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/ruby-crowned-kinglet/main.png",
    additionalImages: [],
    colors: parseColors("Green, Gray, Yellow")
  },
  {
    id: "7",
    name: "Golden-crowned Sparrow",
    ability: "Golden Glimmer",
    rarity: "common",
    description: "A striking sparrow with a bright golden stripe on its head. They forage in low shrubs and on the ground. Often seen during winter in the Bay Area.",
    funFact: "They sometimes hide their bright golden crown to avoid predators.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/golden-crowned-sparrow/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Yellow, Gray")
  },
  {
    id: "8",
    name: "Barn Swallow",
    ability: "Acrobat Express",
    rarity: "common",
    description: "Sleek, blue-and-rust birds that perform stunning aerial maneuvers. They catch insects mid-flight with precision. Their mud-cup nests often dot barns and bridges.",
    funFact: "Can drink while flying, scooping water mid-air with their beaks.",
    habitat: "urban",
    size: "small",
    imageUrl: "/images/birds/barn-swallow/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Brown, White")
  },
  {
    id: "9",
    name: "Song Sparrow",
    ability: "Melody Maker",
    rarity: "common",
    description: "A common little songbird with streaked brown feathers. Known for their rich, varied songs. They forage low to the ground and in shrubs.",
    funFact: "Their song can vary widely even within a small neighborhood.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/song-sparrow/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray, White")
  },
  {
    id: "10",
    name: "Chestnut-backed Chickadee",
    ability: "Chestnut Chatter",
    rarity: "common",
    description: "Small, energetic birds with warm chestnut-colored backs. They flit through shrubs and trees in mixed flocks. Listen for their high-pitched \"chick-a-dee\" calls.",
    funFact: "Can remember thousands of locations where it caches food.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/chestnut-backed-chickadee/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Black")
  },
  {
    id: "11",
    name: "Killdeer",
    ability: "Broken Wing Trickster",
    rarity: "rare",
    description: "A clever shorebird famous for pretending to have a broken wing to lure predators away from its nest. Found in open fields, mudflats, and shores. Their loud call announces their presence.",
    funFact: "Famous for pretending to have a broken wing to lure predators away from nests.",
    habitat: "coast",
    size: "medium",
    imageUrl: "/images/birds/killdeer/main.png",
    additionalImages: [],
    colors: parseColors("Brown, White, Black")
  },
  {
    id: "12",
    name: "Brewer's Blackbird",
    ability: "Shiny Sneak",
    rarity: "common",
    description: "Glossy black birds with bright yellow eyes. Often found in fields or parking lots, scavenging for seeds and insects. They're highly adaptable to urban areas.",
    funFact: "Uses its bright yellow eyes to intimidate rivals.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/brewers-blackbird/main.png",
    additionalImages: [],
    colors: parseColors("Black, Yellow")
  },
  {
    id: "13",
    name: "Nuttall's Woodpecker",
    ability: "Tree Drummer",
    rarity: "common",
    description: "A small woodpecker that drums energetically on trees to find insects. Found in oak woodlands and suburban areas. Listen for their rapid \"pik-pik\" calls.",
    funFact: "Both sexes help excavate tree cavities, which can be used for decades.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/nuttalls-woodpecker/main.png",
    additionalImages: [],
    colors: parseColors("Black, White, Brown")
  },
  {
    id: "14",
    name: "Lesser Scaup",
    ability: "Diving Dynamo",
    rarity: "rare",
    description: "A medium-sized diving duck that forages underwater for mollusks and aquatic insects. Often seen on lakes and bays during winter. Males have striking black-and-white plumage.",
    funFact: "Can dive up to 6 feet to catch mollusks and aquatic insects.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/lesser-scaup/main.png",
    additionalImages: [],
    colors: parseColors("Black, Gray, White")
  },
  {
    id: "15",
    name: "Oak Titmouse",
    ability: "Tiny Oak Sentinel",
    rarity: "common",
    description: "Small, gray-brown birds that move in flocks through oak trees. They eat insects and seeds, often flicking their tails. Their soft calls are easy to miss if you're not paying attention.",
    funFact: "Sometimes joins mixed flocks with chickadees and nuthatches for safety.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/oak-titmouse/main.png",
    additionalImages: [],
    colors: parseColors("Gray, Brown")
  },
  {
    id: "16",
    name: "Greater Scaup",
    ability: "Big Splash",
    rarity: "rare",
    description: "A diving duck found on open waters, feeding on mollusks and plants. Males have glossy green heads, making them easy to identify. Winter visitor in the Bay Area.",
    funFact: "Males undergo a complete molt each summer, temporarily losing flight ability.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/greater-scaup/main.png",
    additionalImages: [],
    colors: parseColors("Black, Gray, White")
  },
  {
    id: "17",
    name: "Wood Duck",
    ability: "Colorful Cruiser",
    rarity: "rare",
    description: "One of the most colorful ducks in North America with iridescent feathers. Nest in tree cavities near water. Their bright plumage makes them a favorite for photographers.",
    funFact: "Nests in tree cavities and the ducklings leap to the ground shortly after hatching.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/wood-duck/main.png",
    additionalImages: [],
    colors: parseColors("Green, Blue, White, Brown")
  },
  {
    id: "18",
    name: "California Towhee",
    ability: "Scrubby Forager",
    rarity: "common",
    description: "Ground-dwelling sparrow with a plain brown body and friendly demeanor. They scratch through leaf litter for seeds and insects. Common in gardens and parks.",
    funFact: "Can use its long clawed toes to scratch and sift through leaf litter efficiently.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/california-towhee/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray")
  },
  {
    id: "19",
    name: "Cooper's Hawk",
    ability: "Forest Falcon",
    rarity: "rare",
    description: "A medium-sized hawk that navigates forests with agility. Hunts smaller birds and mammals. Watch for their rapid, direct flight through wooded areas.",
    funFact: "Uses incredible speed and agility to chase down small birds in forests.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/coopers-hawk/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray, White")
  },
  {
    id: "20",
    name: "Black-crowned Night-Heron",
    ability: "Night Stalker",
    rarity: "rare",
    description: "A stocky heron active at dusk and night. Feeds on fish and aquatic insects in wetlands. Often seen standing silently along the water's edge.",
    funFact: "Feeds mostly at night, relying on stealth to catch fish.",
    habitat: "wetland",
    size: "large",
    imageUrl: "/images/birds/black-crowned-night-heron/main.png",
    additionalImages: [],
    colors: parseColors("Black, Gray, White")
  },
  {
    id: "21",
    name: "Great Horned Owl",
    ability: "Silent Spinner",
    rarity: "rare",
    description: "A powerful nocturnal hunter with tufted ears. Hunts mammals and birds under the cover of night. Known for their deep hooting calls.",
    funFact: "Known to take prey much larger than itself, including skunks!",
    habitat: "forest",
    size: "large",
    imageUrl: "/images/birds/great-horned-owl/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray, White")
  },
  {
    id: "22",
    name: "Great Blue Heron",
    ability: "Long-Legged Lurker",
    rarity: "common",
    description: "Tall, elegant wader with a slow, deliberate hunting style. Stands motionless in shallow water waiting for fish. Can be spotted along bays, rivers, and ponds.",
    funFact: "Can stand still for long periods, sometimes hours, waiting for fish.",
    habitat: "wetland",
    size: "huge",
    imageUrl: "/images/birds/great-blue-heron/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Gray, White")
  },
  {
    id: "23",
    name: "Red-shouldered Hawk",
    ability: "Sky Siren",
    rarity: "rare",
    description: "Medium-sized raptor with rufous underparts and distinctive call. Hunts in forests and woodlands. Often perched high to watch for prey.",
    funFact: "Prefers forested areas and is rarely seen soaring like other hawks.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/red-shouldered-hawk/main.png",
    additionalImages: [],
    colors: parseColors("Brown, White, Red")
  },
  {
    id: "24",
    name: "Snowy Egret",
    ability: "Elegant Strut",
    rarity: "rare",
    description: "A graceful white heron with black legs and yellow feet. Stalks shallow water for fish with delicate steps. Their striking plumes were once sought for fashion.",
    funFact: "Once nearly hunted to extinction for its beautiful plumes.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/snowy-egret/main.png",
    additionalImages: [],
    colors: parseColors("White, Yellow, Black")
  },
  {
    id: "25",
    name: "Townsend's Warbler",
    ability: "Stripe Surprise",
    rarity: "rare",
    description: "Tiny warbler with bold facial stripes and yellow flanks. Flits through conifers looking for insects. More common in winter in the Bay Area.",
    funFact: "Migrates hundreds of miles each year between breeding and wintering grounds.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/townsends-warbler/main.png",
    additionalImages: [],
    colors: parseColors("Yellow, Black, White")
  },
  {
    id: "26",
    name: "Bushtit",
    ability: "Fluffball Frenzy",
    rarity: "common",
    description: "Very small, fluffy birds that move in large flocks. Constantly foraging in shrubs and trees. Tiny but social, with soft buzzing calls.",
    funFact: "Very social; may roost with dozens of birds snuggled together.",
    habitat: "shrubland",
    size: "tiny",
    imageUrl: "/images/birds/bushtit/main.png",
    additionalImages: [],
    colors: parseColors("Gray, Brown")
  },
  {
    id: "27",
    name: "Allen's Hummingbird",
    ability: "Tiny Torpedo",
    rarity: "common",
    description: "Tiny, agile hummingbird with shimmering green and orange plumage. Feeds on nectar from flowers and sips from feeders. Known for their rapid wingbeats.",
    funFact: "Males perform elaborate hovering displays to attract females.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/allens-hummingbird/main.png",
    additionalImages: [],
    colors: parseColors("Green, Brown, White")
  },
  {
    id: "28",
    name: "House Finch",
    ability: "Chirpy Charm",
    rarity: "common",
    description: "Small, adaptable bird with red coloring on males. Common in urban and suburban areas. Cheerful song fills gardens and feeders.",
    funFact: "Can adapt its song to urban noise, changing pitch and tempo.",
    habitat: "urban",
    size: "small",
    imageUrl: "/images/birds/house-finch/main.png",
    additionalImages: [],
    colors: parseColors("Red, Brown, Gray")
  },
  {
    id: "29",
    name: "Anna's Hummingbird",
    ability: "Ruby Rocket",
    rarity: "common",
    description: "Iridescent green with a fiery red crown. Feeds on nectar and small insects. Often seen hovering near flowers in backyards.",
    funFact: "Can survive cold nights by going into a hibernation-like torpor.",
    habitat: "urban",
    size: "tiny",
    imageUrl: "/images/birds/annas-hummingbird/main.png",
    additionalImages: [],
    colors: parseColors("Green, Gray, Pink")
  },
  {
    id: "30",
    name: "House Sparrow",
    ability: "City Slicker",
    rarity: "common",
    description: "Small, brown-and-gray bird thriving in cities. Eats seeds and scraps. Highly social and adaptable to human environments.",
    funFact: "Extremely adaptable and can thrive almost anywhere humans live.",
    habitat: "urban",
    size: "small",
    imageUrl: "/images/birds/house-sparrow/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray, Black")
  },
  {
    id: "31",
    name: "Spotted Towhee",
    ability: "Spot Dash",
    rarity: "common",
    description: "Ground-foraging sparrow with bold white spots on wings. Known for their long tail flicks. They scratch leaves for insects and seeds.",
    funFact: "Uses its long tail to flush insects out of leaf litter.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/spotted-towhee/main.png",
    additionalImages: [],
    colors: parseColors("Black, White, Brown")
  },
  {
    id: "32",
    name: "American Robin",
    ability: "Red-Breast Beat",
    rarity: "common",
    description: "Familiar orange-breasted bird that forages on lawns for worms. Heralds spring with its morning song. Often seen hopping around open areas.",
    funFact: "Often eats worms by tugging them from the ground using clever techniques.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/american-robin/main.png",
    additionalImages: [],
    colors: parseColors("Red, Gray, White")
  },
  {
    id: "33",
    name: "Red-masked Parakeet",
    ability: "Masked Mischief",
    rarity: "rare",
    description: "Bright green parrot with a red face, often noisy in flocks. Found in urban areas and parks. Exotic but established in some Bay Area neighborhoods.",
    funFact: "Exotic parakeets have established small wild populations in urban Bay Area areas.",
    habitat: "urban",
    size: "small",
    imageUrl: "/images/birds/red-masked-parakeet/main.png",
    additionalImages: [],
    colors: parseColors("Green, Red")
  },
  {
    id: "34",
    name: "Western Scrub-jay",
    ability: "Clever Collector",
    rarity: "common",
    description: "Bold, intelligent bird with blue and gray feathers. Forages on the ground and caches acorns. Known for noisy calls and curious behavior.",
    funFact: "Known to hide acorns and even remember some of the locations later.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/western-scrub-jay/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Gray, White")
  },
  {
    id: "35",
    name: "Steller's Jay",
    ability: "Blue Trickster",
    rarity: "common",
    description: "Striking dark blue and black bird. Found in coniferous forests and parks. Loud, raucous calls and cheeky antics.",
    funFact: "Can mimic hawk calls to scare other birds away from food.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/stellers-jay/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Black")
  },
  {
    id: "36",
    name: "Mallard",
    ability: "Quack Attack",
    rarity: "common",
    description: "Iconic duck with iridescent green head in males. Dabbling behavior in ponds and rivers. Adaptable and widespread.",
    funFact: "Males may \"vamoose\" from mating territories once the female starts nesting.",
    habitat: "wetland",
    size: "large",
    imageUrl: "/images/birds/mallard/main.png",
    additionalImages: [],
    colors: parseColors("Green, Brown, Blue, White")
  },
  {
    id: "37",
    name: "Rock Pigeon",
    ability: "Urban Glide",
    rarity: "common",
    description: "Ubiquitous city bird with gray plumage. Feeds on seeds and scraps. Very adaptable to urban life.",
    funFact: "Can recognize individual human faces and remember them for years.",
    habitat: "urban",
    size: "medium",
    imageUrl: "/images/birds/rock-pigeon/main.png",
    additionalImages: [
      "/images/birds/rock-pigeon/male.png",
      "/images/birds/rock-pigeon/female.png",
      "/images/birds/rock-pigeon/juvenile.png",
      "/images/birds/rock-pigeon/extra.png"
    ],
    colors: parseColors("Gray, White, Black")
  },
  {
    id: "38",
    name: "California Gull",
    ability: "Coastal Squawk",
    rarity: "common",
    description: "Medium-sized gull often found along coasts and estuaries. Opportunistic feeder, loud calls. Common in Bay Area beaches.",
    funFact: "Can drop shellfish from heights to crack them open.",
    habitat: "coast",
    size: "large",
    imageUrl: "/images/birds/california-gull/main.png",
    additionalImages: [],
    colors: parseColors("White, Gray, Black")
  },
  {
    id: "39",
    name: "Western Gull",
    ability: "Beach Boss",
    rarity: "common",
    description: "Large, bold gull of the coast. Dominates beaches and docks. Feeds on fish, garbage, and anything edible.",
    funFact: "Aggressive scavenger that sometimes steals food from other birds.",
    habitat: "coast",
    size: "large",
    imageUrl: "/images/birds/western-gull/main.png",
    additionalImages: [],
    colors: parseColors("White, Gray, Black")
  },
  {
    id: "40",
    name: "Black Oystercatcher",
    ability: "Shell Smasher",
    rarity: "rare",
    description: "Black shorebird with bright orange bill. Feeds on mollusks along rocky shores. Easy to spot due to striking coloring.",
    funFact: "Uses its bright orange bill to pry open mollusks and limpets on rocky shores.",
    habitat: "coast",
    size: "large",
    imageUrl: "/images/birds/black-oystercatcher/main.png",
    additionalImages: [],
    colors: parseColors("Black, Red")
  },
  {
    id: "41",
    name: "Heermann's Gull",
    ability: "Red-Beak Racer",
    rarity: "rare",
    description: "Medium gray gull with a bright red bill. Often forages along the coastline. Migrates in flocks during winter.",
    funFact: "Changes from mostly gray juvenile plumage to adult gray-and-white with red bill.",
    habitat: "coast",
    size: "large",
    imageUrl: "/images/birds/heermanns-gull/main.png",
    additionalImages: [],
    colors: parseColors("Gray, White, Red")
  },
  {
    id: "42",
    name: "Brown Pelican",
    ability: "Dive Bomber",
    rarity: "rare",
    description: "Large coastal bird with long bill and pouch. Dives from heights to catch fish. Iconic along the Pacific Coast.",
    funFact: "Can hold its breath up to 20 seconds while diving for fish.",
    habitat: "coast",
    size: "huge",
    imageUrl: "/images/birds/brown-pelican/main.png",
    additionalImages: [],
    colors: parseColors("Brown, White, Gray")
  },
  {
    id: "43",
    name: "Red-tailed Hawk",
    ability: "Sky Scout",
    rarity: "common",
    description: "Large raptor with a distinctive red tail. Soars high, hunting for small mammals. Often seen perched on poles or trees.",
    funFact: "Can soar for hours without flapping, riding thermal currents.",
    habitat: "forest",
    size: "large",
    imageUrl: "/images/birds/red-tailed-hawk/main.png",
    additionalImages: [],
    colors: parseColors("Brown, White, Red")
  },
  {
    id: "44",
    name: "Turkey Vulture",
    ability: "Thermal Soarer",
    rarity: "common",
    description: "Large scavenger with dark plumage. Circles in thermals looking for carrion. Recognizable by their bald heads.",
    funFact: "Can detect carrion from over a mile away using its excellent sense of smell.",
    habitat: "mountain",
    size: "large",
    imageUrl: "/images/birds/turkey-vulture/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Black, Red")
  },
  {
    id: "45",
    name: "American Crow",
    ability: "Clever Caw",
    rarity: "common",
    description: "Black, intelligent bird with a wide range of calls. Highly adaptable to urban and rural areas. Often seen in flocks.",
    funFact: "Extremely intelligent; can solve complex puzzles and use tools.",
    habitat: "forest",
    size: "large",
    imageUrl: "/images/birds/american-crow/main.png",
    additionalImages: [],
    colors: ["#000000"]
  },
  {
    id: "46",
    name: "Common Raven",
    ability: "Mischief Maker",
    rarity: "common",
    description: "Large black bird with shaggy throat feathers. Known for problem-solving and vocalizations. Found in forests, coasts, and mountains.",
    funFact: "Known for playful behavior and complex problem-solving skills.",
    habitat: "mountain",
    size: "large",
    imageUrl: "/images/birds/common-raven/main.png",
    additionalImages: [],
    colors: ["#000000"]
  },
  {
    id: "47",
    name: "Mourning Dove",
    ability: "Soft Coos",
    rarity: "common",
    description: "Gentle, slender dove with soft cooing calls. Feeds on seeds on the ground. Very common in parks and open areas.",
    funFact: "Can produce two broods of chicks in a single summer.",
    habitat: "urban",
    size: "medium",
    imageUrl: "/images/birds/mourning-dove/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray")
  },
  {
    id: "48",
    name: "Northern Mockingbird",
    ability: "Song Collector",
    rarity: "common",
    description: "A gray, medium-sized songbird famous for its incredible ability to mimic other birds and even mechanical sounds. Often perched in open areas, it belts out a wide variety of songs to defend its territory. Their energetic, curious nature makes them a delight to watch.",
    funFact: "Can mimic over 200 sounds, including other birds and mechanical noises.",
    habitat: "urban",
    size: "medium",
    imageUrl: "/images/birds/northern-mockingbird/main.png",
    additionalImages: [],
    colors: parseColors("Gray, White")
  },
  {
    id: "49",
    name: "Black Phoebe",
    ability: "Flycatch Flick",
    rarity: "common",
    description: "Small black-and-white bird often seen wagging its tail while perched near water. Quick to dart out and snatch flying insects. Common along streams, ponds, and urban waterways.",
    funFact: "Frequently wags its tail while perched, a distinctive behavior.",
    habitat: "wetland",
    size: "small",
    imageUrl: "/images/birds/black-phoebe/main.png",
    additionalImages: [],
    colors: parseColors("Black, White")
  },
  {
    id: "50",
    name: "American Coot",
    ability: "Paddle Prowler",
    rarity: "common",
    description: "Dark water bird with a white bill and lobed feet. Wades and swims in ponds and lakes, often in flocks. Eats aquatic plants and small invertebrates.",
    funFact: "Lobed toes allow them to swim efficiently and walk on soft mud.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/american-coot/main.png",
    additionalImages: [],
    colors: parseColors("Black, White, Red")
  },
  {
    id: "51",
    name: "Dark-eyed Junco",
    ability: "Snow Sprite",
    rarity: "common",
    description: "Small sparrow with dark gray upperparts and a white belly. Forages on the ground for seeds, often hopping in snow or leaf litter. Seen in forests and gardens during winter.",
    funFact: "Can survive cold winters by fluffing feathers and hopping in snow.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/dark-eyed-junco/main.png",
    additionalImages: [],
    colors: parseColors("Gray, White, Black")
  },
  {
    id: "52",
    name: "Cedar Waxwing",
    ability: "Waxwing Whirl",
    rarity: "rare",
    description: "Sleek, silky bird with a crest and bright red wing tips. Loves berries and can often be seen in flocks. Their soft, high-pitched calls are almost musical.",
    funFact: "Sometimes eats fermented berries, which can make them tipsy!",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/cedar-waxwing/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Yellow, Black")
  },
  {
    id: "53",
    name: "Lesser Goldfinch",
    ability: "Golden Glint",
    rarity: "common",
    description: "Tiny bird with bright yellow underparts and dark green-black upperparts. Flits among shrubs and feeders for seeds. Often performs rapid, bouncing flight patterns.",
    funFact: "Can eat seeds while hanging upside-down from a branch.",
    habitat: "shrubland",
    size: "tiny",
    imageUrl: "/images/birds/lesser-goldfinch/main.png",
    additionalImages: [],
    colors: parseColors("Yellow, Black")
  },
  {
    id: "54",
    name: "Double-crested Cormorant",
    ability: "Diving Demon",
    rarity: "common",
    description: "Large, dark water bird with a hooked bill. Expert diver, hunting fish underwater. Found on lakes, rivers, and coastal areas.",
    funFact: "Must spread wings to dry after diving since their feathers aren't waterproof.",
    habitat: "coast",
    size: "large",
    imageUrl: "/images/birds/double-crested-cormorant/main.png",
    additionalImages: [],
    colors: parseColors("Black, Gray")
  },
  {
    id: "55",
    name: "Black-necked Stilt",
    ability: "Stick Legs",
    rarity: "rare",
    description: "Tall, long-legged shorebird with striking black-and-white plumage. Forages in shallow water for crustaceans and insects. Easy to spot with their stick-thin legs.",
    funFact: "Can stand in shallow water on very thin, stick-like legs for long periods.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/black-necked-stilt/main.png",
    additionalImages: [],
    colors: parseColors("Black, White, Pink")
  },
  {
    id: "56",
    name: "Belted Kingfisher",
    ability: "Splash Slicer",
    rarity: "rare",
    description: "Medium-sized bird with shaggy crest and powerful bill. Dives into water to catch fish with precision. Often perches quietly near streams and bays.",
    funFact: "Dives at fish with incredible speed and precision from perches.",
    habitat: "wetland",
    size: "medium",
    imageUrl: "/images/birds/belted-kingfisher/main.png",
    additionalImages: [],
    colors: parseColors("Blue, White, Brown")
  },
  {
    id: "57",
    name: "Cliff Swallow",
    ability: "Aerial Acrobat",
    rarity: "common",
    description: "Small swallow with a squared tail and mud-cup nests under bridges or cliffs. Performs agile aerial maneuvers to catch insects. Travels in large, noisy flocks.",
    funFact: "Builds intricate mud nests on cliffs, bridges, and buildings.",
    habitat: "urban",
    size: "tiny",
    imageUrl: "/images/birds/cliff-swallow/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Brown, White")
  },
  {
    id: "58",
    name: "Acorn Woodpecker",
    ability: "Nutty Knocker",
    rarity: "common",
    description: "Striking black-and-white bird with a red cap. Peck at oak trees for insects and store acorns in \"granaries.\" Found in oak woodlands and parks.",
    funFact: "Stores thousands of acorns in granary trees for winter use.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/acorn-woodpecker/main.png",
    additionalImages: [],
    colors: parseColors("Black, White, Red")
  },
  {
    id: "59",
    name: "Snowy Plover",
    ability: "Sand Sprinter",
    rarity: "rare",
    description: "Tiny pale shorebird that blends into sandy beaches. Runs quickly along the shore looking for small invertebrates. Nesting areas are often protected due to their rarity.",
    funFact: "Nests in scrapes on sandy beaches, camouflaged to avoid predators.",
    habitat: "coast",
    size: "tiny",
    imageUrl: "/images/birds/snowy-plover/main.png",
    additionalImages: [],
    colors: parseColors("White, Brown, Black")
  },
  {
    id: "60",
    name: "Golden-crowned Kinglet",
    ability: "Golden Flicker",
    rarity: "common",
    description: "Very small, energetic bird with a bright golden crown. Flits among conifers searching for insects. Constant motion and high-pitched calls make it fun to spot.",
    funFact: "Flits constantly and can eat more than half its body weight in insects daily.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/golden-crowned-kinglet/main.png",
    additionalImages: [],
    colors: parseColors("Green, Yellow, Black")
  },
  {
    id: "61",
    name: "Lazuli Bunting",
    ability: "Blue Blaze",
    rarity: "rare",
    description: "Brightly colored male with vivid blue and orange plumage. Found in open scrub and edges of forests. Feeds on seeds and insects, often singing from exposed perches.",
    funFact: "Male shows off bright colors during courtship to attract females.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/lazuli-bunting/main.png",
    additionalImages: [],
    colors: parseColors("Blue, White, Black")
  },
  {
    id: "62",
    name: "Pacific Wren",
    ability: "Tiny Warbler",
    rarity: "common",
    description: "Small, brown, highly active wren with a loud, complex song. Forages on branches and logs for insects. Often hidden, but their song gives them away.",
    funFact: "Has one of the loudest songs relative to its tiny size.",
    habitat: "forest",
    size: "tiny",
    imageUrl: "/images/birds/pacific-wren/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Gray, Black")
  },
  {
    id: "63",
    name: "Black-headed Grosbeak",
    ability: "Bold Beak",
    rarity: "rare",
    description: "Medium-sized bird with striking black head and orange underparts. Eats seeds, insects, and fruits. Known for a rich, melodious song during the breeding season.",
    funFact: "Eats large seeds by cracking them with a strong beak.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/black-headed-grosbeak/main.png",
    additionalImages: [],
    colors: parseColors("Orange, Black, White")
  },
  {
    id: "64",
    name: "Western Bluebird",
    ability: "Sky Singer",
    rarity: "common",
    description: "Small, sky-blue bird with a rusty chest. Hunts insects from perches and nests in cavities. Their cheerful song makes them a favorite in gardens and open woodlands.",
    funFact: "Males defend nesting cavities aggressively from competitors.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/western-bluebird/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Orange, White")
  },
  {
    id: "65",
    name: "Violet-green Swallow",
    ability: "Violet Dash",
    rarity: "common",
    description: "Agile aerial bird with metallic green and purple sheen. Nests in cavities or under eaves. Hunts flying insects on the wing, often in large flocks.",
    funFact: "Catches insects mid-air with acrobatic skill, often in large flocks.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/violet-green-swallow/main.png",
    additionalImages: [],
    colors: parseColors("Blue, Green, White")
  },
  {
    id: "66",
    name: "Yellow-rumped Warbler",
    ability: "Yellow Flash",
    rarity: "common",
    description: "Small, active warbler with bright yellow patches on the rump and sides. Forages for insects in shrubs and trees. Winters in Bay Area forests and parks.",
    funFact: "Can digest waxy berries that other birds cannot, allowing winter survival.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/yellow-rumped-warbler/main.png",
    additionalImages: [],
    colors: parseColors("Yellow, Gray, Black, White")
  },
  {
    id: "67",
    name: "Western Tanager",
    ability: "Fiery Feathers",
    rarity: "rare",
    description: "Striking bird with bright red head and yellow body. Forages in conifers for insects and berries. Their vivid colors make them easy to spot during migration.",
    funFact: "Bright colors make males easy to spot during courtship in forests.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/western-tanager/main.png",
    additionalImages: [],
    colors: parseColors("Red, Yellow, Black")
  },
  {
    id: "68",
    name: "Purple Finch",
    ability: "Berry Bandit",
    rarity: "rare",
    description: "Small finch with raspberry-red head and chest (males). Feeds on seeds and berries, often in trees and shrubs. Their cheerful song is melodic and warbling.",
    funFact: "Can raid feeders and berries with bold confidence.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/purple-finch/main.png",
    additionalImages: [],
    colors: parseColors("Red, Brown, White")
  },
  {
    id: "69",
    name: "Brown-headed Cowbird",
    ability: "Sneaky Singer",
    rarity: "common",
    description: "Male has a chocolate-brown head and glossy black body. Known for laying eggs in other birds' nests (brood parasitism). Often found in open woodlands and edges.",
    funFact: "Lays eggs in other birds' nests, leaving them to raise their chicks.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/brown-headed-cowbird/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Black")
  },
  {
    id: "70",
    name: "Pacific-slope Flycatcher",
    ability: "Fly Snatcher",
    rarity: "rare",
    description: "Small, gray-green bird that hunts insects from low perches. Subtle eye-ring and soft calls help identify it. Prefers shaded forests and riparian areas.",
    funFact: "Can spot and catch flying insects with remarkable accuracy.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/pacific-slope-flycatcher/main.png",
    additionalImages: [],
    colors: parseColors("Green, Gray, White")
  },
  {
    id: "71",
    name: "California Thrasher",
    ability: "Twist & Thrash",
    rarity: "rare",
    description: "Large brown songbird with a long, curved bill. Digs through leaf litter for insects and berries. Known for complex, melodious songs.",
    funFact: "Uses its long curved bill to dig through leaf litter for insects.",
    habitat: "shrubland",
    size: "medium",
    imageUrl: "/images/birds/california-thrasher/main.png",
    additionalImages: [],
    colors: ["#8B4513"]
  },
  {
    id: "72",
    name: "American Kestrel",
    ability: "Mini Falcon",
    rarity: "common",
    description: "Tiny, colorful falcon that hovers while hunting small prey. Found in open fields and urban edges. Males have blue-gray wings and chestnut backs.",
    funFact: "Can hover midair while scanning for prey below.",
    habitat: "shrubland",
    size: "small",
    imageUrl: "/images/birds/american-kestrel/main.png",
    additionalImages: [],
    colors: parseColors("Orange, Blue, Gray")
  },
  {
    id: "73",
    name: "Northern Flicker",
    ability: "Tree Tappin'",
    rarity: "common",
    description: "Large woodpecker with spotted underparts and bright yellow wing shafts. Forages on the ground for ants and insects as well as pecking trees. Often seen in suburban yards and woodlands.",
    funFact: "Often forages on the ground for ants, unlike other woodpeckers.",
    habitat: "forest",
    size: "medium",
    imageUrl: "/images/birds/northern-flicker/main.png",
    additionalImages: [],
    colors: parseColors("Brown, Black, Yellow, Red")
  },
  {
    id: "74",
    name: "Hermit Thrush",
    ability: "Woodland Whisperer",
    rarity: "rare",
    description: "Medium-sized brown bird with a spotted chest and a melodious, flute-like song. Prefers dense forests and shrubbery. Often shy and more heard than seen.",
    funFact: "Can sing complex, flute-like songs that echo through forests.",
    habitat: "forest",
    size: "small",
    imageUrl: "/images/birds/hermit-thrush/main.png",
    additionalImages: [],
    colors: parseColors("Brown, White")
  },
  {
    id: "75",
    name: "Peregrine Falcon",
    ability: "Sky Torpedo",
    rarity: "legendary",
    description: "The fastest bird in the world, capable of incredible dives. Hunts birds in mid-air with precision. Often found on cliffs or tall city buildings in the Bay Area.",
    funFact: "Fastest animal on Earth, diving at speeds over 200 mph to catch prey.",
    habitat: "urban",
    size: "medium",
    imageUrl: "/images/birds/peregrine-falcon/main.png",
    additionalImages: [],
    colors: parseColors("Gray, Black, White")
  }
];

export const rarityColors = {
  common: "bg-common",
  rare: "bg-rare", 
  legendary: "bg-legendary"
} as const;

export const habitatIcons = {
  forest: "🌲",
  wetland: "🦆",
  grassland: "🌾",
  mountain: "⛰️",
  desert: "🌵",
  arctic: "❄️",
  ocean: "🌊",
  urban: "🏙️",
  "oak woodland": "🌳",
  gardens: "🌺",
  coast: "🏖️",
  shrubland: "🌿"
} as const;

export const sizeIcons = {
  tiny: "🐣",
  small: "🐦",
  medium: "🦅",
  large: "🦆",
  huge: "🦢"
} as const;
